packaging_format = 2

id = "yeswiki"
name = "YesWiki"
description.en = "Wiki that is quick and easy to use"
description.fr = "Wiki facile et rapide à prendre en main"

version = "4.6.3~ynh1"

maintainers = ["alexAubin","eric_G", "Florian Schmitt", "Nils Van Zuijlen", "Plumf", "12b"]

[upstream]
license = "AGPL-3.0-only"
website = "https://yeswiki.net/"
demo = "https://ferme.yeswiki.net/?CreerSonWiki"
admindoc = "https://yeswiki.net/?doc"
code = "https://github.com/YesWiki/yeswiki"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = true

disk = "100M"
ram.build = "200M"
ram.runtime = "50M"

[install]
  [install.domain]
  type = "domain"

  [install.path]
  type = "path"
  default = "/yeswiki"

  [install.init_main_permission]
  help.en = "If YesWiki is made public anyone will be able to view the wiki"
  help.fr = "Si YesWiki est rendu publique toute personne pourra consulter le wiki"
  type = "group"
  default = "visitors"

  [install.language]
  ask.en = "Choose the application language"
  ask.fr = "Choisissez la langue de l'application"
  type = "select"
  choices = ["fr", "en", "ca", "es", "nl", "pt"]
  default = "fr"

  [install.wikimodel]
  ask.en = "Choose the wiki model"
  ask.fr = "Choisissez le modèle de wiki"
  help.en = "YesWiki installs a default YesWiki installation, CLIC will change default look and add a view with installed yunohost apps."
  help.fr = "YesWiki est une installation par défaut de YesWiki, CLIC change le look et les pages par défaut pour ajouter la vue des applications YunoHost installées."
  type = "select"
  choices = ["YesWiki", "CLIC"]
  default = "YesWiki"

  [install.authprovider]
  ask.en = "Choose the authentification type"
  ask.fr = "Choisissez le système d'authentification"
  help.en = "Choose YunoHost SSO to restrict auth to the YunoHost users, choose YesWiki to have an independant user base managed by YesWiki."
  help.fr = "Choisir YunoHost SSO pour n'utiliser que la base d'utilisateurices de YunoHost ou choisir YesWiki pour une base indépendante gérée par YesWiki."
  type = "select"
  choices = ["YunoHost SSO", "YesWiki"]
  default = "YunoHost SSO"

  [install.admin]
  type = "user"

  [install.admin_email]
  ask.en = "Admin email"
  ask.fr = "Email de l'administrateur"
  type = "email"

  [install.wiki_admin_password]
  ask.en = "Wiki admin password"
  ask.fr = "Mot de passe de l'administrateur du wiki"
  type = "string"
  visible = "authprovider == 'YesWiki'"
  optional = true
  default = ""

  [install.wiki_name]
  ask.en = "Choose the wiki name"
  ask.fr = "Choisissez le nom de votre wiki"
  help.en = "If you want a name with spaces: replace them with %20 for each space."
  help.fr = "Si vous souhaitez un nom avec des espacements : remplacez les par %20 pour chaque espace"
  type = "string"
  default = "YesWiki"

  [install.allow_robots]
  ask.en = "Allow search engines indexing"
  ask.fr = "Permettre l'indexation par les moteurs de recherche"
  type = "boolean"
  default = true

  [install.with_sftp]
  ask.en = "Do you need a SFTP access?"
  ask.fr = "Avez-vous besoin d'un accès SFTP ?"
  type = "boolean"
  default = false

  [install.password]
  type = "string"
  visible = "with_sftp"
  optional = true
  default = ""
  help.en = "This corresponds to the password for SFTP access"
  help.fr = "Corresponds au mot de passe pour l'accès SFTP"

[resources]
  [resources.sources.main]
  url = "https://github.com/YesWiki/yeswiki/releases/download/v4.6.3/yeswiki-v4.6.3.zip"
  sha256 = "2baed651eea3732a162ab56b921d209af64fb2a062ceffcab89f72e36beb0dca"
  autoupdate.strategy = "latest_github_release"
  autoupdate.asset = "yeswiki-v\\d+\\.\\d+\\.\\d+\\.zip"

  [resources.sources.yunohostplugin]
  url = "https://github.com/YesWiki/yeswiki-extension-yunohost/releases/download/v1.0.6/yeswiki-extension-yunohost-v1.0.6.zip"
  sha256 = "4295456d985debae3818659a20abedcc8f61b0a1786983c7c0c207059e5a0de4"
  autoupdate.upstream = "https://github.com/YesWiki/yeswiki-extension-yunohost"
  autoupdate.strategy = "latest_github_release"
  autoupdate.asset = "yeswiki-extension-yunohost-v\\d+\\.\\d+\\.\\d+\\.zip"

  [resources.sources.importerplugin]
  url = "https://github.com/YesWiki/yeswiki-extension-importer/releases/download/v1.0.4/yeswiki-extension-importer-v1.0.4.zip"
  sha256 = "026fa36487b5be257ac610a09ec508588c25afa8c4e186f018834d603e56088d"
  autoupdate.upstream = "https://github.com/YesWiki/yeswiki-extension-importer"
  autoupdate.strategy = "latest_github_release"
  autoupdate.asset = "yeswiki-extension-importer-v\\d+\\.\\d+\\.\\d+\\.zip"

  [resources.sources.ferme]
  url = "https://github.com/YesWiki/yeswiki-extension-ferme/releases/download/v1.2.2/yeswiki-extension-ferme-v1.2.2.zip"
  sha256 = "9075a311523be99576e57e1a2b3d8916bff10b8689678aea81ecbf6684b4b0e4"
  autoupdate.upstream = "https://github.com/YesWiki/yeswiki-extension-ferme"
  autoupdate.strategy = "latest_github_release"
  autoupdate.asset = "yeswiki-extension-ferme-v\\d+\\.\\d+\\.\\d+\\.zip"

  [resources.system_user]
  allow_email = true

  [resources.install_dir]
  group = "www-data:r-x"

  [resources.permissions]
  main.url = "/"

  [resources.apt]
  packages = "mariadb-server, php8.4, php8.4-bcmath, php8.4-cli, php8.4-common, php8.4-curl, php8.4-fpm, php8.4-gd, php8.4-gmp, php8.4-igbinary, php8.4-imagick, php8.4-imap, php8.4-intl, php8.4-mbstring, php8.4-mysql, php8.4-opcache, php8.4-readline, php8.4-sqlite3, php8.4-xml, php8.4-xmlrpc, php8.4-zip, php8.4-dom, php8.4-ldap"

  [resources.database]
  type = "mysql"

  [resources.composer]
  version = "2.9.2"
