test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.wikimodel = "YesWiki"
    args.authprovider = "YunoHost SSO"
    args.wiki_name = "YesWiki"
    args.allow_robots = true
    args.with_sftp = "1"
    args.password = "SuperDuper_StrongPassw0rd"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.2372ed8.name = "4.4.1~ynh1"
