# Add .mjs as a file extension for javascript
include mime.types;
types {
    text/javascript mjs;
}

#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/;

  index index.php;

  # Common parameter to increase upload size limit in conjunction with dedicated php-fpm file
  client_max_body_size 500M;

  try_files $uri $uri/ index.php;
  
  # private folder for YesWiki
  location ~* /(.*/)?private/ {
    deny all;
    return 403;
  }

  # Allow iframe embedding for pages with /iframe or /editiframe in their name
  if ($request_uri ~* "/(iframe|editiframe)([/?&]|$)") {
    more_clear_headers "X-Frame-Options";
    more_set_headers "Content-Security-Policy: frame-ancestors *";
  }

  # Allow CORS for API routes
  if ($request_uri ~* "[/?]api/") {
    more_set_headers "Access-Control-Allow-Origin: *";
    more_set_headers "Access-Control-Allow-Methods: GET, POST, OPTIONS";
    more_set_headers "Access-Control-Allow-Headers: Authorization, Content-Type";
  }
  
  location ~ [^/]\.php(/|$) {
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_with_auth;
  }
}
