#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

if [ -f "/etc/sudoers.d/$app" ]; then
  ynh_backup "/etc/sudoers.d/$app"
fi

ynh_backup "/etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh"
ynh_backup "/etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh"
ynh_backup "/etc/yunohost/hooks.d/post_user_create/${app}_sync_user_importer.sh"
ynh_backup "/etc/yunohost/hooks.d/post_user_delete/${app}_sync_user_importer.sh"

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================
ynh_print_info "Backing up the MySQL database..."

ynh_mysql_dump_db > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
