#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

if [ "${BACKUP_CORE_ONLY:-0}" -eq 1 ]; then
  maintenance_on
  if farm_has_wikis; then
    ynh_print_info "Parking the farm wikis' files out of the safety backup..."
    farm_park
  fi
fi

ynh_backup "$install_dir"

ynh_backup "$data_dir"

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"

if [ -f "/etc/sudoers.d/$app" ]; then
  ynh_backup "/etc/sudoers.d/$app"
fi

if [ -f "/etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh" ]; then
  ynh_backup "/etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh"
fi

if [ -f "/etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh" ]; then
  ynh_backup "/etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh"
fi

ynh_backup "/etc/yunohost/hooks.d/post_user_create/${app}_sync_user_importer.sh"
ynh_backup "/etc/yunohost/hooks.d/post_user_delete/${app}_sync_user_importer.sh"

ynh_print_info "Backing up the MySQL database..."

ynh_mysql_dump_db > db.sql

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
