#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

ynh_app_config_validate() {
    _ynh_app_config_validate

    if [ "${changed[with_sftp]}" == "true" ] && [ $with_sftp -eq 1 ] && [ "$password" == "" ]
    then
        ynh_die --message="You need to set a password to enable SFTP"
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply

    if [ "${changed[with_sftp]}" == "true" ] && [ $with_sftp -eq 1 ]
    then
        ynh_system_user_add_group --username=$app --groups="sftp.app"

        if [ ! "$password" == "" ]
        then
            chpasswd <<< "${app}:${password}"
        fi
    elif [ "${changed[with_sftp]}" == "true" ] && [ $with_sftp -eq 0 ]
    then
        ynh_system_user_del_group --username=$app --groups="sftp.app"
    fi
    
    if [ "${changed[password]}" == "true" ] && [ ! "$password" == "" ]
    then
        chpasswd <<< "${app}:${password}"
    fi

    if [ "${changed[with_app_importer]}" == "true" ] && [ $with_app_importer -eq 1 ]
    then
        app_importer_config_add
        app_importer_hooks_add
        app_importer_sync
    elif [ "${changed[with_app_importer]}" == "true" ] && [ $with_app_importer -eq 0 ]
    then
        app_importer_hooks_remove
        app_importer_config_remove
    fi

}

ynh_app_config_run $1

