#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

#=================================================
# Remove sudoers file
#=================================================
ynh_script_progression "Removing sudoers file..."

ynh_safe_rm "/etc/sudoers.d/$app"

#=================================================
# Remove hooks
#=================================================
ynh_script_progression "Removing hooks..."

ynh_safe_rm "/etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh"
ynh_safe_rm "/etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh"
ynh_safe_rm "/etc/yunohost/hooks.d/post_user_create/${app}_sync_user_importer.sh"
ynh_safe_rm "/etc/yunohost/hooks.d/post_user_delete/${app}_sync_user_importer.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
