#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Recreating the dedicated system user..."

if [ $with_sftp -eq 1 ]
then
    groups="sftp.app"
else
    groups=""
fi

shopt -s expand_aliases
prefix="ynh_"
alias noooOoOOOOoOoooOoOoooUser="${prefix}system_user_create"
noooOoOOOOoOoooOoOoooUser --username=$app --home_dir="$install_dir" --groups="$groups"

if [ -n "$password" ]
then
    chpasswd <<< "${app}:${password}"
fi

ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

ynh_restore "$data_dir"

data_dir_link

ynh_script_progression "Putting the farm wikis' files back..."
farm_unpark

ynh_script_progression "Restoring the MySQL database..."

ynh_mysql_db_shell < ./db.sql

ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/php/$php_version/fpm/pool.d/$app.conf"

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/sudoers.d/$app"

if [ -f "$YNH_CWD/etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh" ]; then
  ynh_restore "/etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh"
fi

if [ -f "$YNH_CWD/etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh" ]; then
  ynh_restore "/etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh"
fi

ynh_restore "/etc/yunohost/hooks.d/post_user_create/${app}_sync_user_importer.sh"
ynh_restore "/etc/yunohost/hooks.d/post_user_delete/${app}_sync_user_importer.sh"

ynh_script_progression "Reloading NGINX web server and PHP-FPM..."

ynh_systemctl --service=php$php_version-fpm --action=reload

ynh_systemctl --service=nginx --action=reload

cron_resume

ynh_script_progression "Restoration completed for $app"
