#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=500M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# TODO : find a way to sync stable extensions list to avoid hardcoded extensions folders to keep
noncore_extensions="$(echo tools/{accountactivationbyemail,advancedsearch,benevolat,ferme,fontautoinstall,importer,ipblock,lms,login-sso,logincas,loginldap,maintenance,multideletepages,nextcloudconnector,publication,qrcode,stats,tabdyn,twolevels,webhooks,yunohost})"
ferme_instances="$(
  cd $install_dir
  for p in $(ls -- */wakka.config.php 2>/dev/null); do dirname "$p"; done
)"
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env wakka.config.php files custom private themes $noncore_extensions $ferme_instances"

ynh_replace --match="yeswiki_release' \?=> \?'.*',$" --replace="yeswiki_release' => '$(ynh_app_upstream_version)'," --file="$install_dir/wakka.config.php"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

# If with_sftp doesn't exist, create it
if [ -z "${with_sftp:-}" ]; then
	with_sftp=0
	ynh_app_setting_set --app=$app --key=with_sftp --value=$with_sftp
  # Ensure password is a setting even if empty, for the config panel
  ynh_app_setting_set --app=$app --key=password --value=""
fi


#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================
ynh_script_progression "Installing Composer dependencies..."

ynh_composer_install
ynh_composer_exec install --no-dev


#=================================================
# ADAPT FILE PERMISSIONS FOR SFTP CHROOT
#=================================================
chown -R $app:www-data "$install_dir"
# Home directory of the user needs to be owned by root to allow
# SFTP connections
chown root:root "$install_dir"
setfacl -m g:$app:r-x "$install_dir"
setfacl -m g:www-data:r-x "$install_dir"
chmod 750 "$install_dir"


#=================================================
# DOWNLOAD AND CONFIGURE YUNOHOST PLUGIN
#=================================================
ynh_script_progression "Upgrading YunoHost plugin..."

# In order to use yunohost extension, we need to provide a cached file with the yunohost version
cache_yunohost_version

# Download yunohost plugin from YesWiki repository
ynh_safe_rm "$install_dir/tools/yunohost"
mkdir -p "$install_dir/tools/yunohost"
ynh_setup_source --dest_dir="$install_dir/tools/yunohost" --source_id="yunohostplugin"

# Download importer plugin from YesWiki repository
ynh_safe_rm "$install_dir/tools/importer"
mkdir -p "$install_dir/tools/importer"
ynh_setup_source --dest_dir="$install_dir/tools/importer" --source_id="importerplugin"

# Ensure that scripts are executable
chmod +x $install_dir/tools/yunohost/private/scripts/*.sh

# Add app user in sudoers to authorize to launch YunoHost CLI commands without password
ynh_config_add --template="sudoers" --destination="/etc/sudoers.d/$app"
chown root:root /etc/sudoers.d/$app

# Add a post app install hook to sync the app importer
mkdir -p /etc/yunohost/hooks.d/post_app_install

chmod 700 /etc/yunohost/hooks.d/post_app_install
ynh_config_add --template="sync_app_importer.sh" --destination="/etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh"
chown root:root /etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh
chmod 700 /etc/yunohost/hooks.d/post_app_install/${app}_sync_app_importer.sh

# Add a post app remove hook to sync the app importer
mkdir -p /etc/yunohost/hooks.d/post_app_remove
chmod 700 /etc/yunohost/hooks.d/post_app_remove
ynh_config_add --template="sync_app_importer.sh" --destination="/etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh"
chown root:root /etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh
chmod 700 /etc/yunohost/hooks.d/post_app_remove/${app}_sync_app_importer.sh

# Add a post user create hook to sync the user importer
mkdir -p /etc/yunohost/hooks.d/post_user_create
chmod 700 /etc/yunohost/hooks.d/post_user_create
ynh_config_add --template="sync_user_importer.sh" --destination="/etc/yunohost/hooks.d/post_user_create/${app}_sync_user_importer.sh"
chown root:root /etc/yunohost/hooks.d/post_user_create/${app}_sync_user_importer.sh
chmod 700 /etc/yunohost/hooks.d/post_user_create/${app}_sync_user_importer.sh

# Add a post user delete hook to sync the user importer
mkdir -p /etc/yunohost/hooks.d/post_user_delete
chmod 700 /etc/yunohost/hooks.d/post_user_delete
ynh_config_add --template="sync_user_importer.sh" --destination="/etc/yunohost/hooks.d/post_user_delete/${app}_sync_user_importer.sh"
chown root:root /etc/yunohost/hooks.d/post_user_delete/${app}_sync_user_importer.sh
chmod 700 /etc/yunohost/hooks.d/post_user_delete/${app}_sync_user_importer.sh

if [ $(grep yunohost_sso_domain "$install_dir/wakka.config.php" | wc -l) = "0" ]; then
  SSO_DOMAIN=$(yunohost domain main-domain | sed -e 's/.*: //')
  ynh_replace --match="'wakka_version'" --replace="'yunohost_sso_domain' => '${SSO_DOMAIN}',\n  'wakka_version'" --file="$install_dir/wakka.config.php"
fi

if [ $(grep yunohost-cli "$install_dir/wakka.config.php" | wc -l) != "0" ]; then
  ynh_replace --match="'yunohost-cli'" --replace="'yunohost-apps'" --file="$install_dir/wakka.config.php"
fi
# ToDo : Add app importer config in wakka.config.php if it is not already there ? (need to find a formid that is not already used)

# use the correct php version in yeswicli
ynh_replace --match="php " --replace="php${php_version} " --file="$install_dir/yeswicli"

# At last, run the YunoHost app importer if its data source is configured
if [ $(grep yunohost-cli "$install_dir/wakka.config.php" | wc -l) != "0" ]; then
  ynh_script_progression "Import YunoHost apps in bazar"
  pushd $install_dir
  ynh_exec_as_app ./yeswicli importer:sync -s yunohost-apps
  popd
fi

#=================================================
# RUN THE MIGRATIONS
#=================================================
pushd $install_dir
ynh_exec_as_app ./yeswicli migrate
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
